### ISSUE TITLE
Is there a way to guarantee that all items are used on the training set?

### ISSUE THREAD

**Issue by franzoni315** [david-cortes/recometrics#4]
I am trying to use recometrics with the surprise package, so that I can compare the explicit feedback strategy with implicit feedback algorithms from other packages. However, when I use the `split_reco_train_test` function, some items are missing on the training set, and the SVD algorithm in this package returns the item embedding matrix with lesser rows than expected, which causes the error

`ValueError: Number of items in 'B' and 'X_test' does not match.`

I am using the movielens-1m dataset, and it contains some items that appear only once in the interaction matrix, and these should have a higher probability of not appearing in the training set. 

The only way I could make this to work is to set `items_test_fraction` to a very low percentage (like 1%), but this would impair the quality of the metrics. Is there a way to ensure that all items are present in the training set?

**Comment by david-cortes** [comment]
Currently, this library doesn't have any option to generate splits with that kind of constraints.

Couple thoughts:
* If the explicit-feedback library that you are using performs mean centering, then maybe you could just fill with zeros for the items that were not in the training data.
* You could use library [cmfrec](https://github.com/david-cortes/cmfrec) for explicit-feedback models - under the default settings, it should fill unseen item factors with zeros. Note that it doesn't have any SVD-based solver though.
* Otherwise, you could look into libraries `softImpute` or `lenskit` which should do this kind of centering if you want to go for the manually-fill-with-zeros approach. They both have SVD-based solvers.
